version: '2'
services:
    serviceregistry-app:
        image: serviceregistry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://serviceregistry-mysql:3306/serviceregistry?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=serviceregistry-elasticsearch:9300
        ports:
            - 8080:8080
    serviceregistry-mysql:
        extends:
            file: mysql.yml
            service: serviceregistry-mysql
    serviceregistry-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: serviceregistry-elasticsearch
